---
- name: postgresql stop
  systemd:
    name: postgresql-11
    state: stopped
  become_user: root

- name: delete and create directory for wal-files archive
  file:
    path: /var/lib/pgsql/11/wal_bck/
    state: "{{ item }}"
    mode: '0700'
  with_items:
    - absent
    - directory

- name: delete and create PGDATA directory
  file:
    path: "{{ PGDATA }}"
    state: "{{ item }}"
    mode: '0700'
  with_items:
    - absent
    - directory

- name: performing pg_basebackup backup
  shell: pg_basebackup --wal-method=stream --format=plain --host pgsqlMaster --port=5432 -U repluser --no-password --write-recovery-conf --progress --verbose --checkpoint=fast -D {{ PGDATA }}

- name: edit recovery.conf first (add lines)
  blockinfile:
    path: "{{ PG_RECOVERY }}"
    block: |
      primary_slot_name = 'standby_slot'

- name: edit postgresql.auto.conf (uncomment line)
  replace:
    path: "{{ PGDATA }}/postgresql.auto.conf"
    regexp: '^#(hot_standby =.*)'
    replace: '\1'

- name: postgresql start
  systemd:
    name: postgresql-11
    state: started
  become_user: root
