---
- name: install epel
  yum:
    name:
    - epel-release

- name: install packages
  yum:
    name:
      - vim
      - vim-enhanced
      - mc
      - screen
      - redhat-lsb-core
      - wget
      - yum-utils
      - htop
      - sudo
      - iotop
      - net-tools
      - elinks
      - lynx
      - bind-utils
      - deltarpm
      - lsof
      - tree
      - traceroute
      - tcpdump
    state: latest

- name: copy .screenrc
  copy: src=screenrc dest=/root/.screenrc owner=root group=root mode=0600
- name: edit bashrc, vimrc
  shell: echo "alias vi='vim'" >> /root/.bashrc && echo "colorscheme desert" >> /etc/vimrc


- name: edit sysctl ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: edit sysctl rp_filter
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 0
    sysctl_set: yes
    state: present
    reload: yes

- name: edit sysctl rp_filter
  sysctl:
    name: net.ipv4.conf.eth1.rp_filter
    value: 0
    sysctl_set: yes
    state: present
    reload: yes

- name: edit sysctl rp_filter
  sysctl:
    name: net.ipv4.conf.eth2.rp_filter
    value: 0
    sysctl_set: yes
    state: present
    reload: yes

- name: disable selinux
  selinux: 
    state: disabled
  notify:
    - system restart
