---
- name: install device-mapper-persistent-data, lvm2
  yum:
    name: device-mapper-persistent-data, lvm2
    state: latest

- name: import docker repo a key from a url
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: add repo docker-ce
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker-ce, docker-ce-cli, containerd.io
  yum:
    name: docker-ce, docker-ce-cli, containerd.io
    state: latest

- name: restart docker
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: download docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: change ownership, group and permissions for docker-compose file
  file:
    path: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: '0755'

- name: create a symbolic link for docker-compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

- name: download bash_completion for docker-compose
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/1.24.1/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    mode: '0644'
