---
- name: install epel
  yum:
    name:
    - epel-release

- name: install packages
  yum:
    name:
      - libselinux-python
      - vim
      - vim-enhanced
      - mc
      - screen
      - ccze
      - redhat-lsb-core
#      - wget
      - yum-utils
      - htop
      - sudo
#      - iftop
      - net-tools
#      - elinks
#      - lynx
      - bind-utils
      - deltarpm
      - lsof
      - tree
      - traceroute
      - tcpdump
      - nmap
#      - iperf3
    state: latest

- name: install packages
  yum:
    name:
      - libselinux-python
      - vim
      - vim-enhanced
      - mc
      - screen
      - ccze
      - redhat-lsb-core
#      - wget
      - yum-utils
      - htop
      - sudo
#      - iftop
      - net-tools
#      - elinks
#      - lynx
      - bind-utils
      - deltarpm
      - lsof
      - tree
      - traceroute
      - tcpdump
      - nmap
#      - iperf3
      - dnsmasq
    state: latest
  when: ansible_facts['hostname'] == "inetRouter"

- name: copy .screenrc
  copy: src=screenrc dest=/root/.screenrc owner=root group=root mode=0600
- name: edit bashrc, vimrc
  shell: echo "alias vi='vim'" >> /root/.bashrc && echo "colorscheme desert" >> /etc/vimrc

- name: edit sysctl.conf inetRouter 1
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: ansible_facts['hostname'] == "inetRouter"

- name: edit sysctl.conf inetRouter 2
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: ansible_facts['hostname'] == "inetRouter"

- name: edit sysctl.conf centralRouter
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: ansible_facts['hostname'] == "centralRouter"

- name: disable selinux
  selinux: 
    state: disabled
  notify:
    - system restart
