---
- name: install epel
  yum:
    name:
    - epel-release

- name: install packages
  yum:
    name:
      - sudo
      - net-tools
      - bind-utils
      - traceroute
      - tcpdump
      - nmap
      - nginx
    state: latest
  notify:
    - nginx restart

- name: routing tuning
  shell: |
    echo "DEFROUTE="no"" >> /etc/sysconfig/network-scripts/ifcfg-eth0
    echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
    echo "DEFROUTE="yes"" >> /etc/sysconfig/network-scripts/ifcfg-eth1
  notify:
    - system restart
