---
- name: install epel
  yum:
    name:
    - epel-release

- name: install packages
  yum:
    name:
      - libselinux-python
      - vim
      - vim-enhanced
      - mc
      - screen
#      - ccze
#      - lnav
      - redhat-lsb-core
#      - wget
      - yum-utils
      - htop
      - sudo
#      - iftop
      - net-tools
#      - elinks
#      - lynx
      - bind-utils
      - deltarpm
      - lsof
      - tree
#      - traceroute
#      - tcpdump
      - nmap
#      - unzip
#      - iperf3
    state: latest

- name: copy .screenrc
  copy: src=screenrc dest=/root/.screenrc owner=root group=root mode=0600
- name: edit bashrc, vimrc
  shell: echo "alias vi='vim'" >> /root/.bashrc && echo "colorscheme desert" >> /etc/vimrc

- name: edit authorized_keys to mysqlMaster
  shell: cat /vagrant/provisioning/01_tuning_OS/files/keys/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
  when: ansible_facts['hostname'] == "mysqlMaster"

- name: copy ssh keys to mysqlSlave
  copy: src=keys/ dest=/home/vagrant/.ssh/ owner=vagrant group=vagrant mode=0600
  when: ansible_facts['hostname'] == "mysqlSlave"

- name: touch .ssh/config on mysqlSlave
  file:
    path: /home/vagrant/.ssh/config
    state: touch
    mode: 0600
  when: ansible_facts['hostname'] == "mysqlSlave"
  become_user: vagrant

- name: edit .ssh/config on mysqlSlave
  blockinfile:
    path: /home/vagrant/.ssh/config
    block: StrictHostKeyChecking=no
  when: ansible_facts['hostname'] == "mysqlSlave"
  become_user: vagrant

- name: disable selinux
  selinux:
    state: disabled
  notify:
    - system restart
