---
- name: install haproxy
  yum:
    name: haproxy
    state: latest

- name: copy haproxy.cfg
  copy: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
  notify:
    - haproxy restart
