---
- name: install packages
  yum:
    name:
      - sudo
      - net-tools
      - bind-utils
      - traceroute
      - tcpdump
      - nmap
    state: latest
    
- name: edit sysctl.conf
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: copy iptables rules
  copy: src=knock.sh dest=/home/vagrant owner=vagrant group=vagrant mode=0755

- name: routing tuning
  shell: |
    echo "DEFROUTE="no"" >> /etc/sysconfig/network-scripts/ifcfg-eth0
    echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
    echo "DEFROUTE="yes"" >> /etc/sysconfig/network-scripts/ifcfg-eth1

  notify:
    - system restart
